### ISSUE TITLE
uninitialized constant Sprockets::Rails::VERSION (NameError)

### ISSUE THREAD

**Issue by dideler** [rails/sprockets-rails#132]
In the process of upgrading from Rails 4.0 to 4.1, I had to upgrade the [bootstrap_form](https://github.com/bootstrap-ruby/rails-bootstrap-forms/) gem, which upgraded the sprocket-rails gem.

``` diff
@@ -200,7 +200,7 @@ GEM
       multi_json (~> 1.0)
       rack (~> 1.0)
       tilt (~> 1.1, != 1.3.0)
-    sprockets-rails (2.1.1)
+    sprockets-rails (2.1.2)
       actionpack (>= 3.0)
       activesupport (>= 3.0)
       sprockets (~> 2.8)
@@ -236,7 +236,7 @@ DEPENDENCIES
   binding_of_caller
   bootstrap-datepicker-rails (~> 1.1.1.11)
   bootstrap-sass (~> 3.1.1)
-  bootstrap_form (~> 2.0.1)
+  bootstrap_form (~> 2.1.0)
   capybara
   coffee-rails (~> 4.0.0)
   devise
```

But now `rails server` crashes when it starts.

```
$ rails s
=> Booting Thin
=> Rails 4.1.0 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Notice: server is listening on all interfaces (0.0.0.0). Consider using 127.0.0.1 (--binding option)
=> Ctrl-C to shutdown server
Exiting
/home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-rails-2.1.2/lib/sprockets/railtie.rb:77:in `block in <class:Railtie>': uninitialized constant Sprockets::Rails::VERSION (NameError)
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.0/lib/active_support/lazy_load_hooks.rb:36:in `call'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.0/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.0/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.0/lib/active_support/lazy_load_hooks.rb:44:in `each'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.0/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.0/lib/rails/application/finisher.rb:64:in `block in <module:Finisher>'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.0/lib/rails/initializable.rb:30:in `instance_exec'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.0/lib/rails/initializable.rb:30:in `run'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.0/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/2.1.0/tsort.rb:345:in `each'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/2.1.0/tsort.rb:345:in `call'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.0/lib/rails/initializable.rb:54:in `run_initializers'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.0/lib/rails/application.rb:288:in `initialize!'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.0/lib/rails/railtie.rb:194:in `public_send'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.0/lib/rails/railtie.rb:194:in `method_missing'
    from /home/dennis/rails-app/config/environment.rb:5:in `<top (required)>'
    from /home/dennis/rails-app/config.ru:3:in `block in <main>'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
    from /home/dennis/rails-app/config.ru:in `new'
    from /home/dennis/rails-app/config.ru:in `<main>'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `eval'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `new_from_string'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:40:in `parse_file'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/server.rb:277:in `build_app_and_options_from_config'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/server.rb:199:in `app'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.0/lib/rails/commands/server.rb:50:in `app'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/server.rb:314:in `wrapped_app'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.0/lib/rails/commands/server.rb:130:in `log_to_stdout'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.0/lib/rails/commands/server.rb:67:in `start'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:81:in `block in server'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:76:in `tap'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:76:in `server'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.0/lib/rails/commands.rb:17:in `<top (required)>'
    from /home/dennis/rails-app/bin/rails:8:in `require'
    from /home/dennis/rails-app/bin/rails:8:in `<top (required)>'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/spring-1.1.2/lib/spring/client/rails.rb:27:in `load'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/spring-1.1.2/lib/spring/client/rails.rb:27:in `call'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/spring-1.1.2/lib/spring/client/command.rb:7:in `call'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/spring-1.1.2/lib/spring/client.rb:26:in `run'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/spring-1.1.2/bin/spring:48:in `<top (required)>'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/spring-1.1.2/lib/spring/binstub.rb:11:in `load'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/spring-1.1.2/lib/spring/binstub.rb:11:in `<top (required)>'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/dennis/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/dennis/rails-app/bin/spring:16:in `<top (required)>'
    from bin/rails:3:in `load'
    from bin/rails:3:in `<main>'
```

Will update the issue as I make progress. Possibly related to bootstrap-ruby/rails-bootstrap-forms#32

**Comment by BTC1M** [comment]
Did you find how to solve this issue ? I have exactly the same
