### ISSUE TITLE
Assets with JPEG extensions are compiled or referenced as JPG in 2.3.0

### ISSUE THREAD

**Issue by remomueller** [rails/sprockets-rails#246]
Hi, I'm running into an issue with sprockets-rails 2.3.0, that does not appear to exist in version 2.2.4 (fixing the version to 2.2.4 in development fixes the issue). Not sure if this is a regression or intended behavior for 2.3.0.

The image is labeled with `.jpeg` in `app/assets/images/myapnea/team/member1.jpeg`, however the converted asset seems to be using `.jpg` which causes the following error to show up on the page in development:

```
Sprockets::Rails::Helper::AssetAliasUsed at /team
Asset was linked to from an alias rather than its exact path. Alias resolving may not be available in production.
Use "myapnea/team/member1.jpg" instead of "myapnea/team/member1.jpeg"
```

Thanks!

**Comment by rafaelfranca** [comment]
It is related with https://github.com/rails/sprockets/issues/42

**Comment by rafaelfranca** [comment]
cc @josh

**Comment by josh** [comment]
Hey @remomueller, can you give sprockets-rails 2.3.1 a try and see if it resolves the error message for you?

**Comment by remomueller** [comment]
Hi @josh, I went ahead and updated to 2.3.1, but I ran into the same error message as before. Did you need any other output that I could provide?

**Comment by josh** [comment]
Can you post a trace. Just wondering if you calling this from a view helper or within a sass file.

**Comment by josh** [comment]
Also what version of sprockets are you using?

**Comment by remomueller** [comment]
We're calling it through image_tag helper in the view, here's the trace:

```
Sprockets::Rails::Helper::AssetAliasUsed in Home#dashboard
Showing /Users/remo/code/ruby/www.myapnea.org/app/views/home/landing.html.haml where line #28 raised:

Asset was linked to from an alias rather than its exact path. Alias resolving may not be available in production.
Use "myapnea/testimonials/steve-testimonial-cropped.jpg" instead of "myapnea/testimonials/steve-testimonial-cropped.jpeg"
Extracted source (around line #28):
              
26      = image_tag 'myapnea/team/redline_200x200.jpg', class: 'round-img round-img-orange hidden-xs'
27      = image_tag 'myapnea/testimonials/larry-testimonial-cropped.png', class: 'round-img round-img-blue hidden-xs'
28      = image_tag 'myapnea/testimonials/steve-testimonial-cropped.jpeg', class: 'round-img round-img-orange hidden-xs'
29      = image_tag 'myapnea/testimonials/DEAN.jpg', class: 'round-img round-img-blue hidden-xs'

/ MISSION

Rails.root: /Users/remo/code/ruby/www.myapnea.org

Application Trace | Framework Trace | Full Trace
sprockets-rails (2.3.1) lib/sprockets/rails/helper.rb:134:in `asset_digest_path'
sprockets-rails (2.3.1) lib/sprockets/rails/helper.rb:85:in `compute_asset_path'
actionview (4.2.1) lib/action_view/helpers/asset_url_helper.rb:135:in `asset_path'
sprockets-rails (2.3.1) lib/sprockets/rails/helper.rb:100:in `asset_path'
actionview (4.2.1) lib/action_view/helpers/asset_url_helper.rb:292:in `image_path'
actionview (4.2.1) lib/action_view/helpers/asset_tag_helper.rb:211:in `image_tag'
app/views/home/landing.html.haml:28:in `_app_views_home_landing_html_haml__2617145238734763061_70276208550980'
actionview (4.2.1) lib/action_view/template.rb:145:in `block in render'
activesupport (4.2.1) lib/active_support/notifications.rb:166:in `instrument'
actionview (4.2.1) lib/action_view/template.rb:333:in `instrument'
actionview (4.2.1) lib/action_view/template.rb:143:in `render'
actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (4.2.1) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (4.2.1) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (4.2.1) lib/action_view/rendering.rb:100:in `_render_template'
actionpack (4.2.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (4.2.1) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (4.2.1) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
actionpack (4.2.1) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
actionpack (4.2.1) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (4.2.1) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (4.2.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
activesupport (4.2.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
app/controllers/home_controller.rb:15:in `dashboard'
actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in `call'
rack (1.6.1) lib/rack/etag.rb:24:in `call'
rack (1.6.1) lib/rack/conditionalget.rb:25:in `call'
rack (1.6.1) lib/rack/head.rb:13:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.1) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.1) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
activerecord (4.2.1) lib/active_record/migration.rb:378:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
config/initializers/quiet_assets.rb:7:in `call_with_quiet_assets'
actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.1) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.1) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.1) lib/rack/lock.rb:17:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
rack (1.6.1) lib/rack/sendfile.rb:113:in `call'
railties (4.2.1) lib/rails/engine.rb:518:in `call'
railties (4.2.1) lib/rails/application.rb:164:in `call'
passenger (5.0.7) lib/phusion_passenger/rack/thread_handler_extension.rb:89:in `process_request'
passenger (5.0.7) lib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
passenger (5.0.7) lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
passenger (5.0.7) lib/phusion_passenger/request_handler.rb:414:in `block (3 levels) in start_threads'
passenger (5.0.7) lib/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'
```

**Comment by remomueller** [comment]
Here are the versions from `Gemfile.lock`

```
    sprockets (3.1.0)
      rack (~> 1.0)
    sprockets-rails (2.3.1)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
```

**Comment by josh** [comment]
Ah, okay.

Just curious if this is working as expected on your current sprocket-rails in production? Cause I think your `/assets/myapnea/team/member1-abc123.jpeg` is probably 404ing in production, which is why I recently added the check. Is there anyway you can confirm this?

The `jpeg` vs `jpg` is a separate issue on its own. Thats being tracked over at https://github.com/rails/sprockets/issues/42 and https://github.com/rails/sprockets/issues/40. Ideally, I'd like either to be acceptable to link against, but it needs some extra care to work in production. Also, we may make static asset skip this extname rename step assuming that doesn't lead to other issues.

**Comment by remomueller** [comment]
The image is currently loading fine in production (https://myapnea.org/assets/myapnea/testimonials/steve-testimonial-cropped-5ceb7d80cd67a7a12063821a1354e0ba.jpeg), we do have sprockets-rails fixed at 2.2.4 though.

**Comment by remomueller** [comment]
My guess is that since the rewrite to `.jpg` is occurring in sprockets, that a fix there would also resolve without further need to change anything in sprockets-rails. I think 2.3.0 appears to not let this error fail silently, and brings it to light, which I think is a good approach for this. I'm happy to wait for a resolution on resolution in rails/sprockets#42.

**Comment by josh** [comment]
Alright, thanks @remomueller! I'll close this issue out here, since like you said, the change will occur in sprockets core rather than in the rails plugin.

Thanks for the debug info!

**Comment by remomueller** [comment]
Not a problem, thanks for help troubleshooting @josh!
