### ISSUE TITLE
Rack Builder error when initializing using Konacha

### ISSUE THREAD

**Issue by saturnflyer** [rails/sprockets-rails#308]
I'm still trying to track down exactly what is causing this error, but when I used the latest version of sprockets-rails 3.0.0 along with konacha 3.7.0 I'm unable to run tests.

If I drop down to version 2.3.3 of sprockets-rails, the error disappears.

I've created a sample rails app that illustrates the problem https://github.com/saturnflyer/rackbuilderbug

Here's the core part of the error (with more detail in the sample app)
```
/Users/jim/.gem/ruby/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:146:in `to_app': missing run or map statement (RuntimeError)
    from /Users/jim/.gem/ruby/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:160:in `block in generate_map'
    from /Users/jim/.gem/ruby/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:160:in `each'
    from /Users/jim/.gem/ruby/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:160:in `generate_map'
    from /Users/jim/.gem/ruby/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:145:in `to_app'
    from /Users/jim/.gem/ruby/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:59:in `app'
    from /Users/jim/.gem/ruby/2.3.0/gems/konacha-3.7.0/lib/konacha/engine.rb:10:in `application'
    from /Users/jim/.gem/ruby/2.3.0/gems/konacha-3.7.0/lib/konacha/engine.rb:40:in `block in <class:Engine>'
```

I'm sorry I don't know exactly what's causing this and I believe that bringing it up here is the right place. My rails 4.2.5 app works with sprockets-rails 2.3.3 but fails after upgrading to 3.0.0.
Can anyone point me in the right direction?
I've done some debugging with pry in the Konacha engine.rb and stepped through as it built its rack app but I don't understand why it throws this error.

I'll be opening a ticket at the konacha repo as well.

Thanks for any help you can offer.

**Comment by saturnflyer** [comment]
Somehow I missed an existing issue over at konacha https://github.com/jfirebaugh/konacha/issues/216
