### ISSUE TITLE
Unitialized constant ActionView::Helpers::TagHelper

### ISSUE THREAD

**Issue by ljromero** [rails/sprockets-rails#354]
I'm trying to run rspec tests in a recent updated ancient app. I just updated Rails (3.2 to 4.0.13), rspec (2.x to 3.4.4) and many other gems. When I try to execute the rspec tests, I get this error in the SprocketsRails gem.

```bash
13:00 $ RAILS_ENV=test bundle exec rspec
/home/user/.rvm/gems/ruby-2.2.3@nostraweb/gems/sprockets-rails-2.3.3/lib/sprockets/rails/legacy_asset_tag_helper.rb:7:in `<module:LegacyAssetTagHelper>': uninitialized constant ActionView::Helpers::TagHelper (NameError)
  from /home/user/.rvm/gems/ruby-2.2.3@nostraweb/gems/sprockets-rails-2.3.3/lib/sprockets/rails/legacy_asset_tag_helper.rb:6:in `<module:Rails>'
  from /home/user/.rvm/gems/ruby-2.2.3@nostraweb/gems/sprockets-rails-2.3.3/lib/sprockets/rails/legacy_asset_tag_helper.rb:4:in `<module:Sprockets>'
  from /home/user/.rvm/gems/ruby-2.2.3@nostraweb/gems/sprockets-rails-2.3.3/lib/sprockets/rails/legacy_asset_tag_helper.rb:3:in `<top (required)>'
  from /home/user/.rvm/gems/ruby-2.2.3@nostraweb/gems/sprockets-rails-2.3.3/lib/sprockets/rails/helper.rb:45:in `require'
  from /home/user/.rvm/gems/ruby-2.2.3@nostraweb/gems/sprockets-rails-2.3.3/lib/sprockets/rails/helper.rb:45:in `<module:Helper>'
  from /home/user/.rvm/gems/ruby-2.2.3@nostraweb/gems/sprockets-rails-2.3.3/lib/sprockets/rails/helper.rb:7:in `<module:Rails>'
  from /home/user/.rvm/gems/ruby-2.2.3@nostraweb/gems/sprockets-rails-2.3.3/lib/sprockets/rails/helper.rb:6:in `<module:Sprockets>'
  from /home/user/.rvm/gems/ruby-2.2.3@nostraweb/gems/sprockets-rails-2.3.3/lib/sprockets/rails/helper.rb:5:in `<top (required)>'
  from /home/user/.rvm/gems/ruby-2.2.3@nostraweb/gems/sprockets-rails-2.3.3/lib/sprockets/railtie.rb:6:in `require'
  from /home/user/.rvm/gems/ruby-2.2.3@nostraweb/gems/sprockets-rails-2.3.3/lib/sprockets/railtie.rb:6:in `<top (required)>'
  from /home/user/.rvm/gems/ruby-2.2.3@nostraweb/gems/railties-4.0.13/lib/rails/all.rb:11:in `require'
  from /home/user/.rvm/gems/ruby-2.2.3@nostraweb/gems/railties-4.0.13/lib/rails/all.rb:11:in `block in <top (required)>'
  from /home/user/.rvm/gems/ruby-2.2.3@nostraweb/gems/railties-4.0.13/lib/rails/all.rb:9:in `each'
  from /home/user/.rvm/gems/ruby-2.2.3@nostraweb/gems/railties-4.0.13/lib/rails/all.rb:9:in `<top (required)>'
  from /home/user/workspace/nostraweb/config/application.rb:3:in `require'
  from /home/user/workspace/nostraweb/config/application.rb:3:in `<top (required)>'
  from /home/user/workspace/nostraweb/config/environment.rb:2:in `require'
  from /home/user/workspace/nostraweb/config/environment.rb:2:in `<top (required)>'
  from /home/user/workspace/nostraweb/spec/rails_helper.rb:3:in `require'
  from /home/user/workspace/nostraweb/spec/rails_helper.rb:3:in `<top (required)>'
  from /home/user/workspace/nostraweb/spec/models/my_model_spec.rb:1:in `require'
  from /home/user/workspace/nostraweb/spec/models/my_model_spec.rb:1:in `<top (required)>'
  from /home/user/.rvm/gems/ruby-2.2.3@nostraweb/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `load'
  from /home/user/.rvm/gems/ruby-2.2.3@nostraweb/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
  from /home/user/.rvm/gems/ruby-2.2.3@nostraweb/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `each'
  from /home/user/.rvm/gems/ruby-2.2.3@nostraweb/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
  from /home/user/.rvm/gems/ruby-2.2.3@nostraweb/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in `setup'
  from /home/user/.rvm/gems/ruby-2.2.3@nostraweb/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
  from /home/user/.rvm/gems/ruby-2.2.3@nostraweb/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
  from /home/user/.rvm/gems/ruby-2.2.3@nostraweb/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
  from /home/user/.rvm/gems/ruby-2.2.3@nostraweb/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
  from /home/user/.rvm/gems/ruby-2.2.3@nostraweb/bin/rspec:23:in `load'
  from /home/user/.rvm/gems/ruby-2.2.3@nostraweb/bin/rspec:23:in `<main>'
  from /home/user/.rvm/gems/ruby-2.2.3@nostraweb/bin/ruby_executable_hooks:15:in `eval'
  from /home/user/.rvm/gems/ruby-2.2.3@nostraweb/bin/ruby_executable_hooks:15:in `<main>'
```

It is very strange because if we open the legacy_asset_tag_helper class, we can see that this class is only loaded for Rails 2.x and 3.x (and my app is running in Rails 4.0.13). Maybe I forget to upgrade some gem or something else?

My Gemfile.lock

```ruby
GIT
  remote: https://github.com/cbeer/rsolr-footnotes.git
  revision: 4244af6f7d65d1398250c5a55a6ca38f67a6e686
  specs:
    rsolr-footnotes (0.1.0)
      activesupport
      rails
      rails-footnotes (~> 4.0)
      rsolr

GEM
  remote: http://rubygems.org/
  specs:
    actionmailer (4.0.13)
      actionpack (= 4.0.13)
      mail (~> 2.5, >= 2.5.4)
    actionpack (4.0.13)
      activesupport (= 4.0.13)
      builder (~> 3.1.0)
      erubis (~> 2.7.0)
      rack (~> 1.5.2)
      rack-test (~> 0.6.2)
    activemodel (4.0.13)
      activesupport (= 4.0.13)
      builder (~> 3.1.0)
    activerecord (4.0.13)
      activemodel (= 4.0.13)
      activerecord-deprecated_finders (~> 1.0.2)
      activesupport (= 4.0.13)
      arel (~> 4.0.0)
    activerecord-deprecated_finders (1.0.4)
    activerecord-oracle_enhanced-adapter (1.5.6)
    activeresource (4.0.0)
      activemodel (~> 4.0)
      activesupport (~> 4.0)
      rails-observers (~> 0.1.1)
    activesupport (4.0.13)
      i18n (~> 0.6, >= 0.6.9)
      minitest (~> 4.2)
      multi_json (~> 1.3)
      thread_safe (~> 0.1)
      tzinfo (~> 0.3.37)
    addressable (2.3.8)
    annotate (2.4.0)
    arel (4.0.2)
    aws-sdk (1.66.0)
      aws-sdk-v1 (= 1.66.0)
    aws-sdk-v1 (1.66.0)
      json (~> 1.4)
      nokogiri (>= 1.4.4)
    babel-source (5.8.35)
    babel-transpiler (0.7.0)
      babel-source (>= 4.0, < 6)
      execjs (~> 2.0)
    bcrypt (3.1.11)
    bcrypt-ruby (3.1.5)
      bcrypt (>= 3.1.3)
    better_errors (2.1.1)
      coderay (>= 1.0.0)
      erubis (>= 2.6.6)
      rack (>= 0.9.0)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    bourbon (2.1.1)
      sass (>= 3.1)
    browser (2.1.0)
    bson (3.2.6)
    builder (3.1.4)
    byebug (9.0.4)
    cancan (1.6.10)
    capistrano (2.15.7)
      highline
      net-scp (>= 1.0.0)
      net-sftp (>= 2.0.0)
      net-ssh (>= 2.0.14)
      net-ssh-gateway (>= 1.1.0)
    capybara (1.1.2)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      selenium-webdriver (~> 2.0)
      xpath (~> 0.1.4)
    carrierwave (0.11.2)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      json (>= 1.7)
      mime-types (>= 1.16)
      mimemagic (>= 0.3.0)
    celluloid (0.16.0)
      timers (~> 4.0.0)
    childprocess (0.5.9)
      ffi (~> 1.0, >= 1.0.11)
    chronic (0.10.2)
    chunky_png (1.3.5)
    climate_control (0.0.3)
      activesupport (>= 3.0)
    cocaine (0.5.8)
      climate_control (>= 0.0.3, < 1.0)
    coderay (1.1.1)
    coffee-rails (4.1.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.1.x)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.10.0)
    compass (1.0.3)
      chunky_png (~> 1.2)
      compass-core (~> 1.0.2)
      compass-import-once (~> 1.0.5)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
      sass (>= 3.3.13, < 3.5)
    compass-core (1.0.3)
      multi_json (~> 1.0)
      sass (>= 3.3.0, < 3.5)
    compass-h5bp (0.0.5)
      compass
    compass-import-once (1.0.5)
      sass (>= 3.2, < 3.5)
    compass-rails (3.0.2)
      compass (~> 1.0.0)
      sass-rails (< 5.1)
      sprockets (< 4.0)
    concurrent-ruby (1.0.2)
    connection_pool (2.2.0)
    cucumber (2.3.3)
      builder (>= 2.1.2)
      cucumber-core (~> 1.4.0)
      cucumber-wire (~> 0.0.1)
      diff-lcs (>= 1.1.3)
      gherkin (~> 3.2.0)
      multi_json (>= 1.7.5, < 2.0)
      multi_test (>= 0.1.2)
    cucumber-core (1.4.0)
      gherkin (~> 3.2.0)
    cucumber-rails (1.3.0)
      capybara (>= 1.1.2)
      cucumber (>= 1.1.8)
      nokogiri (>= 1.5.0)
    cucumber-wire (0.0.1)
    daemons (1.2.3)
    database_cleaner (0.8.0)
    debug_inspector (0.0.2)
    devise (3.0.4)
      bcrypt-ruby (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      warden (~> 1.2.3)
    devise-encryptable (0.2.0)
      devise (>= 2.1.0)
    devise_security_extension (0.10.0)
      devise (>= 3.0.0, < 4.0)
      railties (>= 3.2.6, < 5.0)
    diff-lcs (1.2.5)
    elasticsearch (1.0.17)
      elasticsearch-api (= 1.0.17)
      elasticsearch-transport (= 1.0.17)
    elasticsearch-api (1.0.17)
      multi_json
    elasticsearch-transport (1.0.17)
      faraday
      multi_json
    em-websocket (0.5.1)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.6.0)
    erubis (2.7.0)
    eventmachine (1.2.0.1)
    execjs (2.6.0)
    factory_girl (4.7.0)
      activesupport (>= 3.0.0)
    faraday (0.9.2)
      multipart-post (>= 1.2, < 3)
    fast-stemmer (1.0.2)
    ffi (1.9.10)
    foreman (0.62.0)
      thor (>= 0.13.6)
    formatador (0.2.5)
    gherkin (3.2.0)
    guard (2.13.0)
      formatador (>= 0.2.4)
      listen (>= 2.7, <= 4.0)
      lumberjack (~> 1.0)
      nenv (~> 0.1)
      notiffany (~> 0.0)
      pry (>= 0.9.12)
      shellany (~> 0.0)
      thor (>= 0.18.1)
    guard-compat (1.2.1)
    guard-livereload (2.5.2)
      em-websocket (~> 0.5)
      guard (~> 2.8)
      guard-compat (~> 1.0)
      multi_json (~> 1.8)
    haml (4.0.7)
      tilt
    haml-rails (0.9.0)
      actionpack (>= 4.0.1)
      activesupport (>= 4.0.1)
      haml (>= 4.0.6, < 5.0)
      html2haml (>= 1.0.1)
      railties (>= 4.0.1)
    hashie (3.4.4)
    highline (1.7.8)
    hitimes (1.2.4)
    html2haml (2.0.0)
      erubis (~> 2.7.0)
      haml (~> 4.0.0)
      nokogiri (~> 1.6.0)
      ruby_parser (~> 3.5)
    html5-rails (0.1.0)
      jquery-rails (>= 2.0)
      railties (>= 3.2)
      thor (~> 0.14)
    http_parser.rb (0.6.0)
    i18n (0.7.0)
    iconv (1.0.4)
    jquery-rails (3.1.4)
      railties (>= 3.0, < 5.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (4.2.1)
      railties (>= 3.2.16)
    json (1.8.3)
    kgio (2.10.0)
    libv8 (3.16.14.15)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    lumberjack (1.0.10)
    mail (2.6.4)
      mime-types (>= 1.16, < 4)
    method_source (0.8.2)
    mime-types (3.0)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0221)
    mimemagic (0.3.0)
    mini_magick (3.8.1)
      subexec (~> 0.2.1)
    mini_portile2 (2.0.0)
    minitest (4.7.5)
    mongoid (4.0.2)
      activemodel (~> 4.0)
      moped (~> 2.0.0)
      origin (~> 2.1)
      tzinfo (>= 0.3.37)
    mongoid_search (0.3.2)
      fast-stemmer (~> 1.0.0)
      mongoid (>= 3.0.0)
    mono_logger (1.1.0)
    moped (2.0.7)
      bson (~> 3.0)
      connection_pool (~> 2.0)
      optionable (~> 0.2.0)
    msgpack (0.5.12)
    multi_json (1.12.1)
    multi_test (0.1.2)
    multipart-post (2.0.0)
    mysql2 (0.3.21)
    nenv (0.3.0)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-sftp (2.1.2)
      net-ssh (>= 2.6.5)
    net-ssh (3.1.1)
    net-ssh-gateway (1.2.0)
      net-ssh (>= 2.6.5)
    nokogiri (1.6.7.2)
      mini_portile2 (~> 2.0.0.rc2)
    notiffany (0.1.0)
      nenv (~> 0.1)
      shellany (~> 0.0)
    oj (2.10.4)
    optionable (0.2.0)
    origin (2.2.0)
    orm_adapter (0.5.0)
    paperclip (4.3.6)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      cocaine (~> 0.5.5)
      mime-types
      mimemagic (= 0.3.0)
    pdfkit (0.8.2)
    protected_attributes (1.1.3)
      activemodel (>= 4.0.1, < 5.0)
    prototype-rails (4.0.1)
      rails (~> 4.0)
    pry (0.10.3)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    quiet_assets (1.1.0)
      railties (>= 3.1, < 5.0)
    rack (1.5.5)
    rack-protection (1.5.3)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    railroady (1.4.2)
    rails (4.0.13)
      actionmailer (= 4.0.13)
      actionpack (= 4.0.13)
      activerecord (= 4.0.13)
      activesupport (= 4.0.13)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.0.13)
      sprockets-rails (~> 2.0)
    rails-footnotes (4.1.8)
      rails (>= 3.2)
    rails-observers (0.1.2)
      activemodel (~> 4.0)
    rails_config (0.4.2)
      activesupport (>= 3.0)
    railties (4.0.13)
      actionpack (= 4.0.13)
      activesupport (= 4.0.13)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    raindrops (0.16.0)
    rake (11.1.2)
    rb-fsevent (0.9.7)
    rb-inotify (0.9.7)
      ffi (>= 0.5.0)
    react-rails (1.7.1)
      babel-transpiler (>= 0.7.0)
      coffee-script-source (~> 1.8)
      connection_pool
      execjs
      rails (>= 3.2)
      tilt
    recursive-open-struct (0.6.5)
    redis (3.0.7)
    redis-actionpack (4.0.1)
      actionpack (~> 4)
      redis-rack (~> 1.5.0)
      redis-store (~> 1.1.0)
    redis-activesupport (4.1.5)
      activesupport (>= 3, < 5)
      redis-store (~> 1.1.0)
    redis-namespace (1.5.2)
      redis (~> 3.0, >= 3.0.4)
    redis-rack (1.5.0)
      rack (~> 1.5)
      redis-store (~> 1.1.0)
    redis-rails (4.0.0)
      redis-actionpack (~> 4)
      redis-activesupport (~> 4)
      redis-store (~> 1.1.0)
    redis-store (1.1.7)
      redis (>= 2.2)
    ref (2.0.0)
    resque (1.25.2)
      mono_logger (~> 1.0)
      multi_json (~> 1.0)
      redis-namespace (~> 1.3)
      sinatra (>= 0.9.2)
      vegas (~> 0.1.2)
    resque-scheduler (2.5.5)
      mono_logger (~> 1.0)
      redis (~> 3.0.4)
      resque (~> 1.25.1)
      rufus-scheduler (~> 2.0.24)
    resque_mailer (2.3.0)
      actionmailer (>= 3.0)
    rest-client (1.6.7)
      mime-types (>= 1.16)
    rsolr (1.0.2)
      builder (>= 2.1.2)
    rspec-core (3.4.4)
      rspec-support (~> 3.4.0)
    rspec-expectations (3.4.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.4.0)
    rspec-mocks (3.4.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.4.0)
    rspec-rails (3.4.2)
      actionpack (>= 3.0, < 4.3)
      activesupport (>= 3.0, < 4.3)
      railties (>= 3.0, < 4.3)
      rspec-core (~> 3.4.0)
      rspec-expectations (~> 3.4.0)
      rspec-mocks (~> 3.4.0)
      rspec-support (~> 3.4.0)
    rspec-support (3.4.1)
    ruby-oci8 (2.2.2)
    ruby-prof (0.15.9)
    ruby_dep (1.3.1)
    ruby_parser (3.8.2)
      sexp_processor (~> 4.1)
    rubyzip (1.2.0)
    rufus-scheduler (2.0.24)
      tzinfo (>= 0.3.22)
    rvm-capistrano (1.5.6)
      capistrano (~> 2.15.4)
    sass (3.4.22)
    sass-rails (5.0.4)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    searchkick (1.3.0)
      activemodel
      elasticsearch (>= 1)
      hashie
    selenium-webdriver (2.38.0)
      childprocess (>= 0.2.5)
      multi_json (~> 1.0)
      rubyzip (~> 1.0)
      websocket (~> 1.0.4)
    sexp_processor (4.7.0)
    shellany (0.0.1)
    sidekiq (3.4.1)
      celluloid (~> 0.16.0)
      connection_pool (>= 2.1.1)
      json
      redis (>= 3.0.6)
      redis-namespace (>= 1.3.1)
    simple_form (3.2.1)
      actionpack (> 4, < 5.1)
      activemodel (> 4, < 5.1)
    sinatra (1.4.7)
      rack (~> 1.5)
      rack-protection (~> 1.4)
      tilt (>= 1.3, < 3)
    slop (3.6.0)
    sprockets (3.6.0)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (2.3.3)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    subexec (0.2.3)
    therubyracer (0.12.2)
      libv8 (~> 3.16.14.0)
      ref
    thin (1.6.4)
      daemons (~> 1.0, >= 1.0.9)
      eventmachine (~> 1.0, >= 1.0.4)
      rack (~> 1.0)
    thor (0.19.1)
    thread_safe (0.3.5)
    thrift (0.9.3.0)
    thrift_client (0.9.3)
      thrift (~> 0.9.0)
    tilt (2.0.4)
    timers (4.0.4)
      hitimes
    transit-ruby (0.8.591)
      addressable (~> 2.3.6)
      msgpack (~> 0.5.8)
      oj (~> 2.10.1)
    tzinfo (0.3.49)
    uglifier (1.3.0)
      execjs (>= 0.3.0)
      multi_json (~> 1.0, >= 1.0.2)
    unicorn (5.1.0)
      kgio (~> 2.6)
      raindrops (~> 0.7)
    useragent (0.16.7)
    vegas (0.1.11)
      rack (>= 1.0.0)
    warden (1.2.6)
      rack (>= 1.0)
    websocket (1.0.7)
    whenever (0.9.4)
      chronic (>= 0.6.3)
    will_paginate (3.0.5)
    wkhtmltopdf-binary-edge (0.12.3.0)
    xpath (0.1.4)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  activerecord-oracle_enhanced-adapter (~> 1.5.0)
  activeresource
  annotate (= 2.4.0)
  aws-sdk (< 2.0)
  better_errors
  binding_of_caller
  bourbon (= 2.1.1)
  browser
  byebug
  cancan
  capistrano (~> 2.13)
  capybara (= 1.1.2)
  carrierwave
  coffee-rails
  compass
  compass-h5bp (= 0.0.5)
  compass-rails
  cucumber-rails (= 1.3.0)
  database_cleaner (= 0.8.0)
  devise (~> 3.0.0)
  devise-encryptable
  devise_security_extension
  factory_girl
  foreman (= 0.62.0)
  guard-livereload
  haml
  haml-rails
  html5-rails
  iconv (~> 1.0.3)
  jquery-rails
  jquery-ui-rails (~> 4.2.1)
  mini_magick (~> 3.3)
  mongoid (~> 4.0)
  mongoid_search
  mysql2 (~> 0.3.21)
  nokogiri
  paperclip
  pdfkit
  protected_attributes
  prototype-rails
  quiet_assets
  railroady
  rails (~> 4.0.13)
  rails-footnotes (~> 4.0)
  rails-observers
  rails_config (~> 0.4.2)
  react-rails
  recursive-open-struct (= 0.6.5)
  redis-rails
  redis-store
  resque
  resque-scheduler (~> 2.5.5)
  resque_mailer
  rest-client (= 1.6.7)
  rsolr (= 1.0.2)
  rsolr-footnotes!
  rspec-rails
  ruby-oci8 (~> 2.2.0)
  ruby-prof
  rvm-capistrano
  sass-rails
  searchkick
  selenium-webdriver (~> 2.38.0)
  sidekiq
  simple_form
  sinatra (>= 1.3.0)
  therubyracer
  thin
  thrift (= 0.9.3.0)
  thrift_client (= 0.9.3)
  transit-ruby
  uglifier (< 2)
  unicorn
  useragent
  whenever
  will_paginate (= 3.0.5)
  wkhtmltopdf-binary-edge (~> 0.12.3.0)

BUNDLED WITH
   1.12.5
```

**Comment by rafaelfranca** [comment]
Seems that `ActionView::Helpers::AssetUrlHelper` is not defined in your application so it is trying to load the `legacy_asset_tag_helper` file. Make sure that constant is defined at that point.
