### ISSUE TITLE
Assets compile failing

### ISSUE THREAD

**Issue by ankitrg** [rails/sprockets-rails#400]
Is this because I upgraded sprockets?

```
I, [2017-04-22T09:44:17.036739 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/manifest-d0ff5974b6aa52cf562bea5921840c032a860a91a3512f7fe8f768f6bbe005f6.js
  I, [2017-04-22T09:44:17.037068 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/manifest-d0ff5974b6aa52cf562bea5921840c032a860a91a3512f7fe8f768f6bbe005f6.js.gz
  I, [2017-04-22T09:44:17.037370 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/analyse-071051f4360cd5c591626aa7146c1e46e5c752fe960c340917fb869ad6051e8f.svg
  I, [2017-04-22T09:44:17.037505 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/analyse-071051f4360cd5c591626aa7146c1e46e5c752fe960c340917fb869ad6051e8f.svg.gz
  I, [2017-04-22T09:44:17.037724 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/api-0d31fff8572b5051cb5b278845fa9b963d3e832dd8e0430c616b56bcb821af21.svg
  I, [2017-04-22T09:44:17.037881 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/api-0d31fff8572b5051cb5b278845fa9b963d3e832dd8e0430c616b56bcb821af21.svg.gz
  I, [2017-04-22T09:44:17.038102 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/auto_responder-044536668993c2773b2d503a02357e5971d07d706402498ebd1968e68100040f.svg
  I, [2017-04-22T09:44:17.038224 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/auto_responder-044536668993c2773b2d503a02357e5971d07d706402498ebd1968e68100040f.svg.gz
  I, [2017-04-22T09:44:17.038440 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/construction-ea4e6cab21ea670fe9db0e878f0ecb63b2aa8f3f3d0233fe6c147e73eb2608dc.jpg
  I, [2017-04-22T09:44:17.038754 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/drag_n_drop-dfbd3e929c08210e364fe8ac5d1920057743a9ec4be370c2536c6f89502b3f7e.svg
  I, [2017-04-22T09:44:17.038874 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/drag_n_drop-dfbd3e929c08210e364fe8ac5d1920057743a9ec4be370c2536c6f89502b3f7e.svg.gz
  I, [2017-04-22T09:44:17.039100 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/ease_to_access-96fc1ca3d29319309f6ac58cd2aeb5c063bf5e4b0334040c4e7223ca59f80410.svg
  I, [2017-04-22T09:44:17.039208 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/ease_to_access-96fc1ca3d29319309f6ac58cd2aeb5c063bf5e4b0334040c4e7223ca59f80410.svg.gz
  I, [2017-04-22T09:44:17.039438 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/economical-d27899bc50f61b65bdd7189afbb4b052fbaba6e8a01d02c4cd708619c474d4fd.svg
  I, [2017-04-22T09:44:17.039555 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/economical-d27899bc50f61b65bdd7189afbb4b052fbaba6e8a01d02c4cd708619c474d4fd.svg.gz
  I, [2017-04-22T09:44:17.039767 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/email-dd96acb4f2f0df66bba261e0f9ed6080648dbed4ed27be036b7683774f668a20.svg
  I, [2017-04-22T09:44:17.039888 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/email-dd96acb4f2f0df66bba261e0f9ed6080648dbed4ed27be036b7683774f668a20.svg.gz
  I, [2017-04-22T09:44:17.040107 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/embeded-1df43dc2c4eb5253c25347b67e9c86b2be21e389233c9bf3aff9a2fbf7fa56be.svg
  I, [2017-04-22T09:44:17.040227 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/embeded-1df43dc2c4eb5253c25347b67e9c86b2be21e389233c9bf3aff9a2fbf7fa56be.svg.gz
  I, [2017-04-22T09:44:17.041086 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/formester_images/SVG_160x160/formester_01_svg-89c664b0dd47b200c570165cedcb6f144c6b17d01bab3f915f9e37a81d977974.svg
  I, [2017-04-22T09:44:17.041206 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/formester_images/SVG_160x160/formester_01_svg-89c664b0dd47b200c570165cedcb6f144c6b17d01bab3f915f9e37a81d977974.svg.gz
  I, [2017-04-22T09:44:17.041436 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/formester_images/SVG_160x160/formester_02_inverse_transparent-e245a362674b51def7e0628b6b759355b74a749bedb8d399cd97b2d4703eade2.svg
  I, [2017-04-22T09:44:17.044779 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/formester_images/SVG_160x160/formester_02_inverse_transparent-e245a362674b51def7e0628b6b759355b74a749bedb8d399cd97b2d4703eade2.svg.gz
  I, [2017-04-22T09:44:17.045068 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/formester_images/SVG_160x160/formester_02_svg_inverse-798baa9ec37aaa8d1ce8caf88ebb3a0b47e565bb75a30979d93f13744c85d7c5.svg
  I, [2017-04-22T09:44:17.045189 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/formester_images/SVG_160x160/formester_02_svg_inverse-798baa9ec37aaa8d1ce8caf88ebb3a0b47e565bb75a30979d93f13744c85d7c5.svg.gz
  I, [2017-04-22T09:44:17.045419 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/formester_images/SVG_160x160/formester_03_WB-0dbd02caa6e9b51a4b29c96fa1d146fbc587545ccc3a6a1c326f83677909a336.svg
  I, [2017-04-22T09:44:17.045538 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/formester_images/SVG_160x160/formester_03_WB-0dbd02caa6e9b51a4b29c96fa1d146fbc587545ccc3a6a1c326f83677909a336.svg.gz
  I, [2017-04-22T09:44:17.045769 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/formester_images/SVG_160x160/formester_04_BW-269c5fd3125ff54aa774b297fbb872bca65c6cf339d7db842ef7520100284d06.svg
  I, [2017-04-22T09:44:17.045882 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/formester_images/SVG_160x160/formester_04_BW-269c5fd3125ff54aa774b297fbb872bca65c6cf339d7db842ef7520100284d06.svg.gz
  I, [2017-04-22T09:44:17.046114 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/formester_images/favicons/android-chrome-192x192-0860b68dd1daa2a1a81a20e3fc1e3303d13dc8208f76ed71db1924c1e0ca885f.png
  I, [2017-04-22T09:44:17.046378 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/formester_images/favicons/android-chrome-512x512-8110b0435f04265ae36262346aef9cec830b487df8a1c67261bbf8c41644c388.png
  I, [2017-04-22T09:44:17.046659 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/formester_images/favicons/apple-touch-icon-dc5866b644fdde3f83fea7eeb0ca2c9bfca03390fc1b1b6b8711ddeffc12802e.png
  I, [2017-04-22T09:44:17.046945 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/formester_images/favicons/browserconfig-c348b0d6df3d900efef7ae4b4dfc8b62b1737b04d09d4584fef243211c266866.xml
  I, [2017-04-22T09:44:17.047234 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/formester_images/favicons/favicon-16x16-8330a67b9647c2eb26aa60cb8025a7f6bb85a9156eb19c10d14bf6745c8a7577.png
  I, [2017-04-22T09:44:17.047488 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/formester_images/favicons/favicon-32x32-64b14cfc0f140c74803445e2993170ae016291b3856723f78e935bd8e4dae3e8.png
  I, [2017-04-22T09:44:17.047741 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/formester_images/favicons/favicon-ff6ade9f10fd3b0f73b113e19ea0df695bf5a44d41a69e2686b69dbc59333aa3.ico
  I, [2017-04-22T09:44:17.047858 #23035]  INFO -- : Writing /var/app/ondeck/public/assets/formester_images/favicons/favicon-ff6ade9f10fd3b0f73b113e19ea0df695bf5a44d41a69e2686b69dbc59333aa3.ico.gz
  rake aborted!
  NoMethodError: undefined method `split' for nil:NilClass
  /var/app/ondeck/vendor/bundle/gems/sprockets-4.0.0.beta4/lib/sprockets/http_utils.rb:17:in `match_mime_type?'
  /var/app/ondeck/vendor/bundle/gems/sprockets-4.0.0.beta4/lib/sprockets/manifest.rb:297:in `block in exporters_for_asset'
  /var/app/ondeck/vendor/bundle/gems/sprockets-4.0.0.beta4/lib/sprockets/manifest.rb:296:in `each'
  /var/app/ondeck/vendor/bundle/gems/sprockets-4.0.0.beta4/lib/sprockets/manifest.rb:296:in `exporters_for_asset'
  /var/app/ondeck/vendor/bundle/gems/sprockets-4.0.0.beta4/lib/sprockets/manifest.rb:183:in `block in compile'
  /var/app/ondeck/vendor/bundle/gems/sprockets-4.0.0.beta4/lib/sprockets/manifest.rb:125:in `block (2 levels) in find'
  /var/app/ondeck/vendor/bundle/gems/sprockets-4.0.0.beta4/lib/sprockets/base.rb:81:in `find_all_linked_assets'
  /var/app/ondeck/vendor/bundle/gems/sprockets-4.0.0.beta4/lib/sprockets/manifest.rb:124:in `block in find'
  /var/app/ondeck/vendor/bundle/gems/sprockets-4.0.0.beta4/lib/sprockets/manifest.rb:123:in `each'
  /var/app/ondeck/vendor/bundle/gems/sprockets-4.0.0.beta4/lib/sprockets/manifest.rb:123:in `find'
  /var/app/ondeck/vendor/bundle/gems/sprockets-4.0.0.beta4/lib/sprockets/manifest.rb:165:in `compile'
  /var/app/ondeck/vendor/bundle/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
  /var/app/ondeck/vendor/bundle/gems/sprockets-4.0.0.beta4/lib/rake/sprocketstask.rb:148:in `with_logger'
  /var/app/ondeck/vendor/bundle/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
  /var/app/ondeck/vendor/bundle/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
  /opt/rubies/ruby-2.3.1/bin/bundle:23:in `load'
  /opt/rubies/ruby-2.3.1/bin/bundle:23:in `<main>'
  Tasks: TOP => assets:precompile
  (See full trace by running task with --trace) (Executor::NonZeroExitStatus)
```

Here is my log! Can someone tell me is this happening because I just upgrade my gems.

**Comment by ankitrg** [comment]
Sorry for the issue! I think the error message should be more informative.
