### ISSUE TITLE
For some reason sprockets seems to fail on large javascript files.

### ISSUE THREAD

**Issue by FlowerCannon** [rails/sprockets-rails#413]
HI, I'm developing a Rails application for a year using Rails 4.2.6 and sprockets 4.0.0.beta5 + babel-transpiler so I can use ES6.

It were going well in one year of development until a very strange thing began to happen: After a merge branch my tests started to fail and sprockets was complaining some files were not declared in manifest.js file but they was declared! It also started to pop up `ActionView::Template::Error: TypeError: /Users/[myhome]/____/projects/[proje]/app/assets/javascripts/[the file].es6: Cannot read property 'error' of undefined`.

I'm not sure but it seems to be related with file size. When I run tests with part of the code removed it runs just fine:

    > rake test:controllers
    Run options: --seed 28340
    # Running:

    ..............................................

    Finished in 17.351602s, 2.6511 runs/s, 6.3395 assertions/s.

    46 runs, 110 assertions, 0 failures, 0 errors, 0 skips`

And this is the output without removing code:

    > rake test:controllers
    Run options: --seed 31756

    # Running:

    .....E...........E.........E..................

    Finished in 8.931830s, 5.1501 runs/s, 11.7557 assertions/s.

      1) Error:
    PasswordResetsControllerTest#test_must_get_edit_when_valid_digest:
    ActionView::Template::Error: TypeError: /Users/[thehome]/____/projects/[theproject]/app/assets/javascripts/projects_index.es6: Cannot read property 'error' of undefined
        

      2) Error:
    ProjectsControllerTest#test_must_get_index:
    ActionView::Template::Error: TypeError: /Users/\/____/projects/[theproject]/app/assets/javascripts/projects_index.es6: Cannot read property 'error' of undefined
        app/views/layouts/application.html.erb:164:in `_app_views_layouts_application_html_erb__3159220365243512236_70324501665840'
        app/controllers/projects_controller.rb:8:in `index'
        test/controllers/projects_controller_test.rb:11:in `block in <class:ProjectsControllerTest>'

      3) Error:
    WelcomeControllerTest#test_should_get_index:
    ActionView::Template::Error: Asset `welcome_index.js` was not declared to be precompiled in production.
    Declare links to your assets in `app/assets/config/manifest.js`.

      //= link welcome_index.js
    and restart your server
        app/views/layouts/application.html.erb:164:in `_app_views_layouts_application_html_erb__3159220365243512236_70324447182320'
        test/controllers/welcome_controller_test.rb:5:in `block in <class:WelcomeControllerTest>'

    46 runs, 105 assertions, 0 failures, 3 errors, 0 skips

**Comment by FlowerCannon** [comment]
Sorry everyone. After debugging and investigating a lot I discovered that (maybe) the issue is actually related to babel transpiler. It seems that ExecJS and node are messing up precompiling and confusing sprockets.
