### ISSUE TITLE
config.assets.quiet = true causing crash for rails-4.2.10

### ISSUE THREAD

**Issue by albertnetymk** [rails/sprockets-rails#422]
With `config.assets.quiet = true` in `config/environments/development.rb`, I got the following error message on loading the home page.
```
Unexpected error while processing request: undefined method `reopen' for nil:NilClass
        /home/albert/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.10/lib/active_support/core_ext/kernel/reporting.rb:106:in `ensure in capture'
        /home/albert/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.10/lib/active_support/core_ext/kernel/reporting.rb:106:in `capture'
        /home/albert/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.10/lib/active_support/logger.rb:64:in `block (3 levels) in broadcast'
        /home/albert/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.10/lib/active_support/logger_silence.rb:19:in `silence'
        /home/albert/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.10/lib/active_support/logger.rb:62:in `block (2 levels) in broadcast'
        /home/albert/.rvm/gems/ruby-2.3.1/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:11:in `call'
...
```

Removing the `quiet` option, and restart with `rails s` makes the home page load, and I can see a lot of info message on my terminal where I started `rails s`.

I am using ruby (2.3.1), rails (4.2.10) and sprockets-rails (3.2.1).

PS: I have gone through all issues containing `quiet` keyword, but can't find anything relevant.

**Comment by albertnetymk** [comment]
Updating to ruby 2.5.0 and rails 5.1.4 seems to fix the issue.
