### ISSUE TITLE
Getting `LoadError: cannot load such file -- sass` even when `config.assets.css_compressor = nil` (want to remove sass completely)

### ISSUE THREAD

**Issue by jasonfb** [rails/sprockets-rails#521]
**Rails 6.1.3**
**Sprockets 3.7.2**

I'm working on Rails 6.1 app where I actually want to remove the old sass-rails gem and, ideally, NOT replace it with the new gem because our app does not use sass whatsoever.

Unfortunately, I am also running into this LoadError: cannot load such file -- sass on my mailers only for outgoing mail (although they are not using SASS at all)

the stacktrace of my crash is here: https://gist.github.com/jasonfb-swift/e2e72599efeedfa0eb6063c1e4a42d6a

in my application.rb I have the css preprocessor set to nil

 config.assets.css_compressor = nil
I have searched my app for any further references to sass but can't find any.

I could install the sassc-rails gem as a replacement, but ideally, I don't want to, because our app does not use SASS (or SCSS) whatsoever, so we don't want it. Is there a dependency in my version of Sprockets that makes sass required? 
It appears that this error `LoadError: cannot load such file -- sass` only happens from mailers (devise mailers), the rest of the app boots fine 

```
2023-06-15T21:23:47.808Z pid=89947 tid=4nhb WARN: LoadError: cannot load such file -- sass
2023-06-15T21:23:47.808Z pid=89947 tid=4nhb WARN: /Users/jason/.rvm/gems/ruby-2.7.6/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:15:in `require'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:15:in `require'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-3.7.2/lib/sprockets/autoload/sass.rb:1:in `<main>'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-3.7.2/lib/sprockets/sass_processor.rb:47:in `initialize'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-3.7.2/lib/sprockets/sass_processor.rb:26:in `new'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-3.7.2/lib/sprockets/sass_processor.rb:26:in `instance'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-3.7.2/lib/sprockets/sass_processor.rb:30:in `call'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:23:in `block in call'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-3.7.2/lib/sprockets/utils.rb:200:in `dfs'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:24:in `call'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-3.7.2/lib/sprockets/base.rb:92:in `[]'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:358:in `find_asset'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:348:in `find_debug_asset'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:230:in `block in lookup_debug_asset'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:243:in `block in resolve_asset'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:242:in `each'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:242:in `detect'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:242:in `resolve_asset'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:229:in `lookup_debug_asset'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:171:in `block in stylesheet_link_tag'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:170:in `map'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:170:in `stylesheet_link_tag'
/Users/jason/August/swift/app/views/devise/mailer/invitation_instructions.html.erb:6:in `_app_views_devise_mailer_invitation_instructions_html_erb___418198370533361567_135620'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionview-6.1.3.1/lib/action_view/base.rb:247:in `public_send'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionview-6.1.3.1/lib/action_view/base.rb:247:in `_run'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionview-6.1.3.1/lib/action_view/template.rb:154:in `block in render'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/notifications.rb:205:in `instrument'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionview-6.1.3.1/lib/action_view/template.rb:345:in `instrument_render_template'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionview-6.1.3.1/lib/action_view/template.rb:152:in `render'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionview-6.1.3.1/lib/action_view/renderer/template_renderer.rb:61:in `block (2 levels) in render_template'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/notifications.rb:203:in `block in instrument'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/notifications.rb:203:in `instrument'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionview-6.1.3.1/lib/action_view/renderer/template_renderer.rb:56:in `block in render_template'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionview-6.1.3.1/lib/action_view/renderer/template_renderer.rb:75:in `render_with_layout'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionview-6.1.3.1/lib/action_view/renderer/template_renderer.rb:55:in `render_template'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionview-6.1.3.1/lib/action_view/renderer/template_renderer.rb:11:in `render'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionview-6.1.3.1/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionview-6.1.3.1/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionview-6.1.3.1/lib/action_view/rendering.rb:117:in `block in _render_template'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionview-6.1.3.1/lib/action_view/base.rb:273:in `in_rendering_context'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionview-6.1.3.1/lib/action_view/rendering.rb:116:in `_render_template'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionview-6.1.3.1/lib/action_view/rendering.rb:103:in `render_to_body'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionpack-6.1.3.1/lib/abstract_controller/rendering.rb:25:in `render'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionmailer-6.1.3.1/lib/action_mailer/base.rb:958:in `block in collect_responses_from_templates'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionmailer-6.1.3.1/lib/action_mailer/base.rb:955:in `each'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionmailer-6.1.3.1/lib/action_mailer/base.rb:955:in `each'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionmailer-6.1.3.1/lib/action_mailer/base.rb:955:in `map'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionmailer-6.1.3.1/lib/action_mailer/base.rb:955:in `collect_responses_from_templates'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionmailer-6.1.3.1/lib/action_mailer/base.rb:933:in `collect_responses'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionmailer-6.1.3.1/lib/action_mailer/base.rb:841:in `mail'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/devise-4.8.0/lib/devise/mailers/helpers.rb:19:in `devise_mail'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/devise_invitable-2.0.5/lib/devise_invitable/mailer.rb:9:in `invitation_instructions'
/Users/jason/August/swift/app/mailers/august_mailer.rb:6:in `invitation_instructions'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionpack-6.1.3.1/lib/abstract_controller/base.rb:228:in `process_action'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionpack-6.1.3.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionpack-6.1.3.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionpack-6.1.3.1/lib/abstract_controller/base.rb:165:in `process'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionmailer-6.1.3.1/lib/action_mailer/rescuable.rb:25:in `block in process'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionmailer-6.1.3.1/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionmailer-6.1.3.1/lib/action_mailer/rescuable.rb:24:in `process'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionview-6.1.3.1/lib/action_view/rendering.rb:39:in `process'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionmailer-6.1.3.1/lib/action_mailer/base.rb:615:in `block in process'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/notifications.rb:203:in `block in instrument'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/notifications.rb:203:in `instrument'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionmailer-6.1.3.1/lib/action_mailer/base.rb:614:in `process'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionmailer-6.1.3.1/lib/action_mailer/message_delivery.rb:128:in `block in processed_mailer'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionmailer-6.1.3.1/lib/action_mailer/message_delivery.rb:127:in `tap'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionmailer-6.1.3.1/lib/action_mailer/message_delivery.rb:127:in `processed_mailer'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/actionmailer-6.1.3.1/lib/action_mailer/message_delivery.rb:118:in `deliver_now'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/devise-4.8.0/lib/devise/models/authenticatable.rb:204:in `send_devise_notification'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/devise_invitable-2.0.5/lib/devise_invitable/models.rb:210:in `deliver_invitation'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/devise_invitable-2.0.5/lib/devise_invitable/models.rb:163:in `block in invite!'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/mongoid-7.2.1/lib/mongoid/interceptable.rb:135:in `run_callbacks'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/devise_invitable-2.0.5/lib/devise_invitable/models.rb:152:in `invite!'
/Users/jason/August/swift/app/jobs/invite_user_job.rb:13:in `perform'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activejob-6.1.3.1/lib/active_job/execution.rb:48:in `block in perform_now'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activejob-uniqueness-0.2.4/lib/active_job/uniqueness/active_job_patch.rb:54:in `block (2 levels) in <module:ActiveJobPatch>'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:126:in `instance_exec'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/i18n-1.10.0/lib/i18n.rb:328:in `with_locale'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activejob-6.1.3.1/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:126:in `instance_exec'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activejob-6.1.3.1/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:126:in `instance_exec'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activejob-6.1.3.1/lib/active_job/instrumentation.rb:21:in `block in instrument'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/notifications.rb:203:in `block in instrument'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/notifications.rb:203:in `instrument'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activejob-6.1.3.1/lib/active_job/instrumentation.rb:31:in `instrument'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activejob-6.1.3.1/lib/active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:126:in `instance_exec'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activejob-6.1.3.1/lib/active_job/logging.rb:22:in `block in tag_logger'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/tagged_logging.rb:37:in `tagged'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/tagged_logging.rb:99:in `tagged'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activejob-6.1.3.1/lib/active_job/logging.rb:22:in `tag_logger'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activejob-6.1.3.1/lib/active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:126:in `instance_exec'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:137:in `run_callbacks'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activejob-6.1.3.1/lib/active_job/execution.rb:47:in `perform_now'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activejob-6.1.3.1/lib/active_job/execution.rb:25:in `block in execute'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activejob-6.1.3.1/lib/active_job/railtie.rb:47:in `block (4 levels) in <class:Railtie>'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/execution_wrapper.rb:88:in `wrap'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/reloader.rb:72:in `block in wrap'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/execution_wrapper.rb:84:in `wrap'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/reloader.rb:71:in `wrap'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activejob-6.1.3.1/lib/active_job/railtie.rb:46:in `block (3 levels) in <class:Railtie>'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:126:in `instance_exec'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:137:in `run_callbacks'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activejob-6.1.3.1/lib/active_job/execution.rb:23:in `execute'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activejob-6.1.3.1/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sidekiq-6.5.0/lib/sidekiq/processor.rb:196:in `execute_job'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sidekiq-6.5.0/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sidekiq-6.5.0/lib/sidekiq/middleware/chain.rb:144:in `block in invoke'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sidekiq-throttled-0.17.0/lib/sidekiq/throttled/middleware.rb:14:in `call'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sidekiq-6.5.0/lib/sidekiq/middleware/chain.rb:146:in `block in invoke'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sidekiq-6.5.0/lib/sidekiq/middleware/chain.rb:149:in `invoke'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sidekiq-6.5.0/lib/sidekiq/processor.rb:163:in `block in process'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sidekiq-6.5.0/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sidekiq-6.5.0/lib/sidekiq/job_retry.rb:115:in `local'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sidekiq-6.5.0/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sidekiq-6.5.0/lib/sidekiq/rails.rb:14:in `block in call'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/execution_wrapper.rb:88:in `wrap'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/reloader.rb:72:in `block in wrap'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/execution_wrapper.rb:88:in `wrap'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.3.1/lib/active_support/reloader.rb:71:in `wrap'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sidekiq-6.5.0/lib/sidekiq/rails.rb:13:in `call'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sidekiq-6.5.0/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sidekiq-6.5.0/lib/sidekiq/processor.rb:257:in `stats'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sidekiq-6.5.0/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sidekiq-6.5.0/lib/sidekiq/job_logger.rb:13:in `call'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sidekiq-6.5.0/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sidekiq-6.5.0/lib/sidekiq/job_retry.rb:82:in `global'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sidekiq-6.5.0/lib/sidekiq/processor.rb:124:in `block in dispatch'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sidekiq-6.5.0/lib/sidekiq/job_logger.rb:39:in `prepare'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sidekiq-6.5.0/lib/sidekiq/processor.rb:123:in `dispatch'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sidekiq-6.5.0/lib/sidekiq/processor.rb:162:in `process'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sidekiq-6.5.0/lib/sidekiq/processor.rb:78:in `process_one'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sidekiq-6.5.0/lib/sidekiq/processor.rb:68:in `run'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sidekiq-6.5.0/lib/sidekiq/component.rb:8:in `watchdog'
/Users/jason/.rvm/gems/ruby-2.7.6/gems/sidekiq-6.5.0/lib/sidekiq/component.rb:17:in `block in safe_thread'
```

**Comment by jasonfb** [comment]
Although the app boots fine with `bin/rails s`, I also see this error when I run `bin/rails assets:precompile`

however, when I run `bin/rails assets:precompile`, I do not see a full stack trace, only the line `LoadError: cannot load such file -- sass` before it aborts

```
➤ YN0000: Done with warnings in 1s 677ms
rails aborted!
LoadError: cannot load such file -- sass
/Users/jason/August/swift/bin/rails:11:in `<top (required)>'
/Users/jason/August/swift/bin/spring:15:in `<top (required)>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```
